import type { Metadata } from 'next';

const title = 'deQuiz';
const description =
  'deQuiz is an innovative platform for creating and minting generative NFTs based on user interactions with quizzes. Each NFT is unique and procedurally-generated by AI.';
const url = 'http://dequiz.app/';
const previewImage = `${url}preview.webp`;

export const mainMeta: Metadata = {
  title,
  description,
  applicationName: title,
  viewport: 'width=device-width, initial-scale=1',
  keywords: ['deQuiz', 'quiz', 'NFT', 'AI', 'Crypto'],
  openGraph: {
    title,
    description,
    url,
    type: 'website',
    images: [
      {
        url: previewImage,
        alt: title,
      },
    ],
  },
  twitter: {
    site: '@deQuiz',
    card: 'summary_large_image',
    title,
    description,
    images: [
      {
        url: previewImage,
        alt: title,
      },
    ],
  },
};
